### ISSUE TITLE
Allow DefaultHttpClient to throw more detailed 5xx exceptions

### ISSUE THREAD

**Issue by ben512** [bytefish/FcmJava#27]
I have implemented a customized IRetryStrategy to do exponential backoff, and a simple fcm server to return 5xx results to test its behavior.

However, current implementation of DefaultHttpClient only throws FcmRetryAfterException if response code is between [500, 600), AND have a "Retry-After" header.

Does FCM always include "Retry-After" header in 5xx responses? If not, it would be nice to throw some specific 5xx exceptions from DefaultHttpClient to allow users to process them separately from just a FcmGeneralException.

Thanks!

**Comment by bytefish** [comment]
I will add more specific errors in the next release. I think the Exceptions should also carry the original HTTP Status Code, otherwise they are impossible to find out on the caller side.

**Comment by bytefish** [comment]
The ``FcmGeneralException`` now contains the HttpStatusCode and the ReasonPhrase. I know, that this may not be useful, because you may need access to the original headers. At the moment I question myself about the separation of the projects: I don't know how to provide access to the raw ``HttpResponse`` using the ``fcmjava-core`` and ``fcmjava-client`` modules.

Including the HttpStatusCode and Http ReasonPhrase is a first attempt to make it easier to differentiate between ``FcmGeneralExceptions``. I will think about how to provide access to the original headers.

**Comment by bytefish** [comment]
Initial Update in Version 2.2.
