### ISSUE TITLE
FCM java conflic with Log4j

### ISSUE THREAD

**Issue by xthaohg** [bytefish/FcmJava#36]
when i used your lib. My project cant writting log. I use Log4j-1.2.15.jar  for writting log.

Excuse me, I'm using google transale.

**Comment by bytefish** [comment]
I think the problem here is, that a dependency of FcmJava has its own log4j, which might cause problems.

There is a great project, that shows how to do logging and exclude the log4j dependencies coming with FcmJava: 

* https://github.com/ralscha/blog/tree/master/push/server

Take a look at the pom file to see how to exclude the problematic dependencies: 

* https://github.com/ralscha/blog/blob/master/push/server/pom.xml#L59
