### ISSUE TITLE
any plan to add support for new http v1 api?

### ISSUE THREAD

**Issue by xmeng1** [bytefish/FcmJava#37]
Any plan to add support for new HTTP v1 api?

**Comment by bytefish** [comment]
I will take a look at it. 😎

**Comment by xmeng1** [comment]
Great!
I am working on a java project will use FCM server, I prepare to use the new v1 api.

**Comment by Mistic92** [comment]
Firebase Messaging was integrated also into Firebase Admin Java 
https://firebase.google.com/docs/admin/setup

**Comment by bytefish** [comment]
Thanks for the information! This makes FcmJava obsolete, I will update the README. 😎

**Comment by Mistic92** [comment]
Not exactly. Firebase sdk is a little painful if you want to send multiple messages. Also need to use Map<String,String> instead of just class. 
Maybe just use it internally?

**Comment by bytefish** [comment]
@Mistic92 You are totally right. I had a brief look through the code and providing a thin wrapper over it makes sense. I probably dismissed FcmJava too quick. 😅 @tmysik When writing a wrapper I could also take a look at the exponential backoff. But it's hard to plan anything at the moment, because I have not much time for open source.

**Comment by tmysik** [comment]
@bytefish I totally understand. Thanks for your feedback.

**Comment by bytefish** [comment]
I decided to not support the new FCM HTTP API and not develop the library any further. The official Firebase SDK contains messaging and it should be used instead of FcmJava.
