### ISSUE TITLE
FCM Admin API

### ISSUE THREAD

**Issue by sheldon-sminq** [bytefish/FcmJava#38]
We are confused with the difference between this library and the 

https://github.com/firebase/firebase-admin-java

**Comment by bytefish** [comment]
This library was written at a time, when the official Firebase Admin SDK for Java did **not** support the Cloud Messaging API. The most recent release of the Firebase Admin SDK **now also contains the Cloud Messaging**, so the official SDK can be used instead of this library. You can find the official Firebase Admin SDK for Java at: https://firebase.google.com/docs/admin/setup.

Updated the README.

**Comment by klem231188** [comment]
At that time, you really saved life of many developpers.
Thank you again for your great library !

**Comment by culebras** [comment]
Yeah, it was a great library.

**Comment by bytefish** [comment]
@klem231188 @culebras Thanks for the nice words and your valuable input along the way. 😎
