### ISSUE TITLE
Exception sending NotificationUnicastMessage

### ISSUE THREAD

**Issue by ChristianSchab** [bytefish/FcmJava#5]
Sending a NotificationUnicastMessage causes a exception because "multicast_id" is not an expected field in the response.

Example Code:
```
String rcpt = "fyw...uJJLzSUlxnQXImRTbpLuxt";
FcmMessageOptions options = FcmMessageOptions.builder().setTimeToLive(Duration.ofHours(1)).build();
NotificationPayload payload = new NotificationPayload("Test title", "body", null, null, null, null, null,
				"https://www.example.com/", null, null, null, null);
NotificationUnicastMessage notificationMessage = new NotificationUnicastMessage(options, rcpt, payload);
new FcmClient(PropertiesBasedSettings.createFromDefault()).send(notificationMessage);
```

Exception:
```
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: 
java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException:
Unrecognized field "multicast_id" (class de.bytefish.fcmjava.responses.UnicastMessageResponse),
 not marked as ignorable (4 known properties: "error", "messageId", "message_id", "errorCode"])
 at [Source: {"multicast_id":798132...98933,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:14819091...f9fd7ecd"}]}; line: 1, column: 144] 
(through reference chain: de.bytefish.fcmjava.responses.UnicastMessageResponse["multicast_id"])
```

**Comment by bytefish** [comment]
Thanks! I'll fix it. 👍

**Comment by ChristianSchab** [comment]
@bytefish Probably its already fixed by #3 (+@JsonIgnoreProperties(ignoreUnknown = true)
but it's missing in Maven!?

**Comment by bytefish** [comment]
It would be wrong to simply ignore it. Probably I misinterpreted the FCM documentation on response messages.

**Comment by bytefish** [comment]
I have renamed the Response to FcmMessageResponse, because there is apparently only one Response Message for Unicast and Multicast messages in Firebase Clound Messaging. Please let me know if version 0.5 fixes the issue.

Version 0.5 should be available within the next hours, when the Central Maven Repositories are synced.

**Comment by ChristianSchab** [comment]
Versions 0.5 of fcmjava-client is still missing on maven  
https://mvnrepository.com/artifact/de.bytefish.fcmjava/fcmjava-client

**Comment by bytefish** [comment]
I am sorry, that's my fault. I didn't double check the uploaded staging repository in Maven. And chances are good it faulted on my side and the fcmjava-client module was never uploaded. 😓 I have created a Version 0.6 now and double checked the uploaded artifacts. 

Sometimes the Central Maven Repository had problems, when I was updating packages. That's why I am going to 0.6 directly. It will take two hours or so again.

Sorry. 😌

**Comment by ChristianSchab** [comment]
Sorry, but there is still no version 0.6 in maven repository.
Could you perhaps check it again?

Thank you a lot!

**Comment by bytefish** [comment]
Yes, I noticed this aswell. Let's wait until tommorow and if it isn't synced, I will open an issue with Sonatype. I staged the repository, closed it and released it like I did for all other releases. I also checked the content of the release.

**Comment by bytefish** [comment]
It's like the Central Repository is listening and synced some moments ago: http://central.maven.org/maven2/de/bytefish/fcmjava/fcmjava-client/0.6/. It should be available now.

**Comment by bytefish** [comment]
Please let me know, if this update fixes the issue. 👍

**Comment by ChristianSchab** [comment]
I just tested it and now it works!
Thank you a lot!

**Comment by bytefish** [comment]
Great! Thanks again for the feedback and raising the issue. 👍
